### ISSUE TITLE
Error in Building "distribution"

### ISSUE THREAD

**Issue by parrot1234** [sharmalab/MEDIator#10]
![Screenshot from 2021-03-23 14-41-40](https://user-images.githubusercontent.com/49876007/112122070-e9ba3b80-8be5-11eb-8774-c0d46ade5589.png)
[INFO] ---------------------< edu.emory.bmi:distribution >---------------------
[INFO] Building distribution 1.0-SNAPSHOT                                 [6/6]
[INFO] --------------------------------[ pom ]---------------------------------
[WARNING] The POM for edu.emory.bmi:documentation:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for MEDIator 1.0-SNAPSHOT:
[INFO] 
[INFO] MEDIator ........................................... SUCCESS [  0.002 s]
[INFO] modules ............................................ SUCCESS [  0.171 s]
[INFO] mediator-core ...................................... SUCCESS [  1.407 s]
[INFO] mediator-webapp .................................... SUCCESS [  0.705 s]
[INFO] mediator-client .................................... SUCCESS [  0.019 s]
[INFO] distribution ....................................... FAILURE [  0.021 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.414 s
[INFO] Finished at: 2021-03-23T14:37:54+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project distribution: Could not resolve dependencies for project edu.emory.bmi:distribution:pom:1.0-SNAPSHOT: Could not find artifact edu.emory.bmi:documentation:jar:1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :distribution

**Comment by pradeeban** [comment]
I just did a git clone and then "mvn package" on a new server, and it builds fine with no errors.

Please follow the README on the commands on building it.
